# Generated by Django 3.0.4 on 2020-07-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfile',
            old_name='user_name',
            new_name='comment',
        ),
    ]
