# Generated by Django 3.0.4 on 2020-07-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200713_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='number',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
