# Generated by Django 3.0.4 on 2020-07-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200713_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='number',
            field=models.IntegerField(),
        ),
    ]
